pgm708_hw02.pdf: pgm708_hw02.tex
	pdflatex $<

clean:
	rm -f pgm708_hw02.aux
	rm -f pgm708_hw02.log
	rm -f pgm708_hw02.blg
	rm -f pgm708_hw02.bbl

spotless: clean
	rm -f pgm708_hw02.pdf

.PHONY: clean spotless
